---
- name: Install ES apt packages
  apt: pkg=elasticsearch state=latest
  environment:
    ES_SKIP_SET_KERNEL_PARAMETERS: "{{ 'true' if elk_elasticsearch_skip_kernel_settings else 'false' }}"
  become: yes
  when: ansible_os_family == 'Debian'
  notify: Restart elasticsearch

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest
  become: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  become: yes
  notify: Restart elasticsearch

- name: Make monit to look after ES
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit/conf.d/elasticsearch.monitrc.conf
    owner=root group=root mode=644
  become: yes
  notify: Restart monit
  when: elk_install_monit