---

- name: Install Kibana apt packages
  apt: pkg=kibana state=latest
  become: yes
  when: ansible_os_family == 'Debian'
  notify: Restart kibana

- name: Generate kibana htpassword
  shell:
    echo "{{ elk_kibana_user }}:$(openssl passwd -crypt {{ elk_kibana_password }}):kibana" |tee .kibana.htpasswd
  args:
    chdir: /etc/nginx/conf.d
    creates: /etc/nginx/conf.d/.kibana.htpasswd
  become: yes
  register: http_pass_gen
  when: elk_kibana_user is defined and elk_kibana_password is defined and elk_kibana_user != ''

- name: Kibana htpassword file permissions
  file:
    path=/etc/nginx/conf.d/.kibana.htpasswd
    owner={{ elk_nginx_user }} group=root mode=400
  become: yes
  when: http_pass_gen|changed
    
- name: Nginx config file
  template:
    src=kibana-default.j2
    dest=/etc/nginx/conf.d/kibana.conf
    owner=root group=root mode=644
  become: yes
  notify: Restart nginx

- name: Make monit to look after Kibana
  template:
    src=kibana.monitrc.conf.j2
    dest=/etc/monit/conf.d/kibana.monitrc.conf
    owner=root group=root mode=644
  become: yes
  notify: Restart monit
  when: elk_install_monit
