---
- name: Install logstash apt packages
  apt: pkg={{ item }} state=present
  with_items:
   - logstash
  become: yes
  when: ansible_os_family == 'Debian'
  notify: Restart logstash

- name: Logstash conf file
  template:
    src="{{ item.src }}"
    dest="/etc/logstash/conf.d/{{ item.dest }}"
    owner=root group=root mode=644
  with_items: "{{ elk_logstash_configs }}"
  become: yes
  notify: Restart logstash

- name: Logstash pattern files
  template:
    src="{{ item.src }}"
    dest="/opt/logstash/patterns/{{ item.dest }}"
    owner=root group=root mode=644
  with_items: "{{ elk_logstash_patterns }}"
  become: yes
  when: elk_logstash_patterns is defined
  notify: Restart logstash

- name: Make monit to look after Logstash
  template:
    src=logstash.monitrc.conf.j2
    dest=/etc/monit/conf.d/logstash.monitrc.conf
    owner=root group=root mode=644
  become: yes
  notify: Restart monit
  when: elk_install_monit