---
- name: Install common apt packages
  apt: pkg={{ item }} state=latest
  with_items: "{{ elk_common_packages }}"
  become: yes

- name: Install monit package
  apt: pkg=monit state=latest
  become: yes
  when: elk_install_monit

- name: Monit conf file
  copy:
    src=monitrc
    dest=/etc/monit/monitrc
    owner=root group=root mode=600
  become: yes
  notify: Restart monit
  when: elk_install_monit

- name: Install Java
  include: java.yml

- name: ES apt GPG key
  apt_key:
    url='https://artifacts.elastic.co/GPG-KEY-elasticsearch'
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install APT https transport
  apt: pkg=apt-transport-https state=latest
  become: yes
  when: ansible_os_family == 'Debian'

- name: Elastic APT Repository
  apt_repository:
    repo="{{ elk_repo }}"
    update_cache=yes
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Logstash
  include: logstash.yml

- name: Install Nginx
  include: nginx.yml

- name: Install Kibana
  include: kibana.yml